version: '3'

networks:
  laravel:

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    ports:
      - "9000:9000"
    volumes:
      - ./backend-master:/var/www/html
    depends_on:
      - postgres
      - redis
    env_file: backend-master/.env
    networks:
      laravel:
        aliases:
          - backend

  admin_app:
    build:
      context: ./
      dockerfile: Dockerfile.admin
    ports:
      - "3000:3000"
    env_file: admin-master/.env
    networks:
      laravel:
        aliases:
          - admin

  webserver:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel
    volumes:
      - ./backend-master:/var/www/html
    depends_on:
      - backend
      - admin_app
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: postgres/.env
    networks:
      laravel:
        aliases:
          - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - laravel
