FROM nginx:stable-alpine

RUN  echo "daemon off;" >> /etc/nginx/nginx.conf
ADD ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/ssl/cert.pem /ssl/cert.pem
COPY ./nginx/ssl/key.pem /ssl/key.pem

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

CMD ["nginx"]
